question_data = [{"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "The Neanderthals were a direct ancestor of modern humans.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "A person can get sunburned on a cloudy day.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "The Doppler effect applies to light.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "The &quot;Gympie Stinger&quot; is the deadliest plant in the world.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "The planet Mars has two moons orbiting it.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "Steel is an alloy of Iron and Carbon.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "Shrimp can swim backwards.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "Type 1 diabetes is a result of the liver working improperly.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "Anatomy considers the forms of macroscopic structures such as organs and organ systems.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, a mollusc, known to be aged as 507 years old.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the body&#039;s inertia.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "In the periodic table, Potassium&#039;s symbol is the letter K.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "Sugar contains fat.", "correct_answer": "False",
                                  "incorrect_answers": ["True"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "Pneumonoultramicroscopicsilicovolcanoconiosis is a synonym for the disease known as silicosis.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "Sound can travel through a vacuum.", "correct_answer": "False",
                                  "incorrect_answers": ["True"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "The most frequent subconscious activity repeated by the human body is blinking.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "&quot;Tachycardia&quot; or &quot;Tachyarrhythmia&quot; refers to a resting heart-rate near or over 100 BPM.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]}]
